import json
from typing import List, Optional, Set
from rdkit import Chem
from rdkit.Chem import AllChem
import re
import gzip
import random
from rdkit.Chem.Draw import rdMolDraw2D
import os
import sys
import enum
from rdkit.Chem import Draw

# --- NEW ENUM TO DESCRIBE REACTION OUTCOMES ---
class ReactionStatus(enum.Enum):
    """Enum to represent the outcome of a reaction test."""
    SUCCESS = "SUCCESS"
    FORWARD_FAILURE = "FORWARD_FAILURE"
    REVERSE_FAILURE = "REVERSE_FAILURE"

# --- NEW FUNCTION TO GENERATE DETAILED DEBUGGING PROMPT ---
def generate_llm_debug_prompt(
    reaction_name: str,
    form_name: str,
    forward_smarts: str,
    forward_reactants: List[str],
    forward_products: List[List[str]],
    reverse_smarts_list: List[str],
    reverse_products_raw: Set[str],
    original_reactants_cleaned: Set[str],
    reverse_products_cleaned: Set[str],
):
    """
    Formats a detailed, copy-paste-friendly debug prompt for an LLM
    when a reverse reaction fails.
    """
    missing_reactants = original_reactants_cleaned - reverse_products_cleaned
    
    prompt = f"""
################################################################################
# LLM DEBUGGING PROMPT: REVERSE REACTION FAILED
################################################################################

Hello, I'm debugging a chemical reaction definition and need your help. A reverse reaction failed to regenerate the original reactants. Here is a complete summary of the failure:

---
1. REACTION CONTEXT
---
- Reaction Name: "{reaction_name}"
- Reactant Form Tested: {form_name}

---
2. FORWARD REACTION (This part appears to be working)
---
- Forward Reaction SMARTS:
`{forward_smarts}`

- These Reactants were provided:
{forward_reactants}

- The Forward Reaction produced this set of products:
{forward_products}

---
3. REVERSE REACTION (This is where the failure occurred)
---
- The products from the forward reaction were then fed into the following Reverse Reaction SMARTS:
{reverse_smarts_list}

- The complete, raw set of molecules generated by the reverse reactions was:
{reverse_products_raw}

---
4. THE FAILURE
---
- My script expected the original reactants to be a subset of the molecules produced by the reverse reaction.
- Cleaned Original Reactants (Expected):
{original_reactants_cleaned}

- Cleaned Reverse Products (Actual):
{reverse_products_cleaned}

- CRITICAL: The following molecules were expected but were NOT found in the reverse reaction products:
{missing_reactants}

---
5. QUESTION
---
Based on the reactants, the forward products, and the failed reverse products, can you identify the error in the reverse reaction SMARTS list and provide a corrected version that would successfully regenerate the missing reactants?

################################################################################
"""
    print(prompt)


def validate_functional_group_defs(reactions):
    func_grp_defs = {}
    for reaction_name, reaction_info in reactions.items():
        for i, func_grp_name in enumerate(reaction_info["functional_groups"]):
            func_grp_smarts = reaction_info["group_smarts"][i]
            if func_grp_name not in func_grp_defs:
                func_grp_defs[func_grp_name] = func_grp_smarts
            else:
                # Check if the existing definition matches the new one
                if func_grp_defs[func_grp_name] != func_grp_smarts:
                    print(f"Warning: Functional group '{func_grp_name}' has multiple definitions:")
                    print(f"  Existing: {func_grp_defs[func_grp_name]}")
                    print(f"  New:      {func_grp_smarts}")
                    # Optionally, you could raise an error here instead of just printing
                    raise ValueError(f"Multiple definitions for functional group '{func_grp_name}'")


def clean_undefined_stereo(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    
    # Check if there are any undefined stereocenters (bonds with ~)
    if '~' in smiles:
        # Remove only undefined stereochemistry, keep defined stereo
        Chem.RemoveStereochemistry(mol)
        return Chem.MolToSmiles(mol)
    else:
        # No undefined stereo, return as-is
        return smiles
    
def force_bond_resolution(smiles):
    if "~" not in smiles:
        return smiles
    
    # First try: just remove the ~ symbol (most common solution)
    try:
        cleaned_smiles = smiles.replace("~", "")
        mol = Chem.MolFromSmiles(cleaned_smiles)
        if mol is not None:
            Chem.SanitizeMol(mol)
            # Let RDKit figure out aromaticity
            Chem.SetAromaticity(mol)
            return Chem.MolToSmiles(mol)
    except Exception as e:
        pass
    
    # Fallback: replace with single bond
    try:
        cleaned_smiles = smiles.replace("~", "-")
        mol = Chem.MolFromSmiles(cleaned_smiles)
        if mol is not None:
            Chem.SanitizeMol(mol)
            return Chem.MolToSmiles(mol)
    except Exception as e:
        pass
    
    return None

def clean_up_smiles(smiles: str) -> Optional[str]:
    """A simple function to clean up common verbose SMILES representations."""
    # TODO: Do these need to be applied to SMILES in the source databases?
    smiles = smiles.replace("[CH2]", "C")
    smiles = smiles.replace("[CH3]", "C")
    smiles = smiles.replace("[CH]", "C")
    smiles = smiles.replace("[CH2-]", "C")
    smiles = smiles.replace("[CH-]", "C")
    smiles = smiles.replace("[C]", "C")
    smiles = smiles.replace("[c]", "c")
    smiles = smiles.replace("[OH-]", "O")
    smiles = smiles.replace("[OH+]", "O")
    smiles = smiles.replace("[IH]", "I")  # Why this?
    smiles = smiles.replace("[NH2+]", "N")
    smiles = smiles.replace("[N]", "N")
    smiles = smiles.replace("[NH2]", "N")
    smiles = smiles.replace("[NH]", "N")
    smiles = smiles.replace("[nH+][n-]", "[nH]n")  # This is a common pattern in azides
    smiles = smiles.replace("N#[N+][N-]", "[N-]=[N+]=N")
    smiles = smiles.replace("[N-][N+]#N", "N=[N+]=[N-]")
    smiles = smiles.replace("C[N+]=C=O", "CN=C=O")
    smiles = smiles.replace("[B]", "B")  # Remove brackets around boron
    # smiles = smiles.replace("[O-]", "O")
    smiles = smiles.replace("[SH-]", "S")
    smiles = smiles.replace("[Cl+]", "Cl")
    smiles = smiles.replace("[Br+]", "Br")
    smiles = smiles.replace("[I+]", "I")
    smiles = smiles.replace("(=[O+])", "(=O)")  # Remove + from carbonyls

    # Strange tetrazole resonance structure I see in some SMILES
    smiles = smiles.replace("C2=N[N+]=NN2", "C2=NN=NN2")
    # Add more replacements if needed

    # Also, smiles should be canonicalized
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        print("Invalid SMILES: ", smiles)
        return None
    
    try:
        # Let RDKit handle hydrogen assignment properly
        Chem.SanitizeMol(mol)
        # Remove explicit hydrogens and let RDKit recalculate
        mol = Chem.RemoveHs(mol)
        smiles = Chem.MolToSmiles(mol, canonical=True)
    except Exception as e:
        print(f"Sanitization failed for {smiles}: {e}")
        return None
    
    # smiles = Chem.MolToSmiles(mol, canonical=True)

    smiles = clean_undefined_stereo(smiles)
    smiles = force_bond_resolution(smiles)

    # if "~" in smiles:
        # import pdb; pdb.set_trace()  # Debugging point to check if undefined stereo is still present

    # Note that this makes invalid SMILES sometimes. But necessary to identify
    # equivalent structures in some cases.
    # smiles = smiles.replace("[nH]", "n")  

    return smiles

def run_rxn(rxn_string: str, reactants_smi_list: List[str], metadata=None)-> List[List[str]]:
    """
    Runs a reaction with a list of reactant SMILES and returns the product sets.
    
    Args:
        rxn_string: The SMARTS reaction string.
        reactants_smi_list: A list of SMILES strings for the reactants.
        
    Returns:
        A list of product sets, where each product set is a list of SMILES strings.
    """
    rxn = AllChem.ReactionFromSmarts(rxn_string)
    
    # Convert all reactant SMILES strings to Mol objects
    reactants_mols = [Chem.MolFromSmiles(smi) for smi in reactants_smi_list]
    
    # Check if any molecule conversion failed
    if any(mol is None for mol in reactants_mols):
        # Handle error, e.g., by logging a warning and returning empty
        print(f"Warning: Could not create one or more reactant molecules from SMILES: {reactants_smi_list}")
        return []

    # Run the reaction. RunReactants expects a sequence (tuple or list) of Mol objects.
    product_sets = rxn.RunReactants(reactants_mols)
    
    predicted_products = []
    for product_set in product_sets:
        product_smiles = []
        for product in product_set:
            if product is not None:
                # Sanitize the molecule to avoid errors in MolToSmiles
                # Chem.SanitizeMol(product)
                smiles = Chem.MolToSmiles(product)
                smiles = clean_up_smiles(smiles)
                if smiles:
                    product_smiles.append(smiles)
                else:
                    print(f"Warning: Failed to clean up product SMILES: {Chem.MolToSmiles(product)}")
                    print(f"Reaction string: {rxn_string}")
                    print(f"Reactants: {reactants_smi_list}")
                    print(f"Metadata: {metadata}")
                    print("")
        if product_smiles:
            # Sort the smiles in each set to make comparisons order-independent
            predicted_products.append(sorted(product_smiles))
            
    return predicted_products

def apply_prereaction(smiles: str, prereaction_strings: List[str]) -> str:
    """
    Apply a list of prereaction strings to standardize a molecule.
    If any prereaction yields products, return the first product from the first successful reaction.
    If no prereaction yields products, return the original SMILES.
    
    Args:
        smiles: The input SMILES string
        prereaction_strings: List of SMARTS reaction strings to try
        
    Returns:
        Standardized SMILES string
    """
    for prereaction_string in prereaction_strings:
        try:
            # Try to run this prereaction on the molecule
            products = run_rxn(prereaction_string, [smiles])
            
            # If we got products, use the first product from the first product set
            if products and len(products) > 0 and len(products[0]) > 0:
                standardized_smiles = products[0][0]  # First product from first set
                print(f"  Applied prereaction: {smiles} -> {standardized_smiles}")
                return standardized_smiles
                
        except Exception as e:
            # If this prereaction fails, try the next one
            print(f"  Prereaction failed: {prereaction_string} on {smiles}: {e}")
            continue
    
    # If no prereaction worked, return original
    print(f"  No prereaction applied to: {smiles}")
    return smiles

def get_forward_reactant_groups(functional_groups: List[str], debug_prereactions: Optional[List[str]] = None) -> List[List[str]]:
    reactant_groups = []

    for functional_group in functional_groups:
        flnm = f"./groups/{functional_group}.smi.gz"
        try:
            with gzip.open(flnm, "rt") as f:
                lines = f.readlines()

                # Pick 100 random reactants from the group
                random.shuffle(lines)
                lines = lines[:100]

                lines = [Chem.MolToSmiles(Chem.MolFromSmiles(line.strip().split("\t")[0])) for line in lines if line.strip()]

                reactant_groups.append(lines)
        except FileNotFoundError:
            print(f"Warning: Functional group file {flnm} not found. Skipping this group.")
            continue

    reactant_groups2 = []
    for i in range(len(reactant_groups[0])):
        # First, do the forward reaction
        forward_reactants = [clean_up_smiles(reactant_groups[j][i]) for j in range(len(reactant_groups))]
        forward_reactants = [f for f in forward_reactants if f]
        
        # Apply debug prereactions if they exist
        if debug_prereactions:
            print(f"Applying debug prereactions to reactant set {i}:")
            standardized_reactants = []
            for j, reactant in enumerate(forward_reactants):
                # Apply prereactions to each reactant individually
                standardized_reactant = apply_prereaction(reactant, debug_prereactions)
                standardized_reactants.append(standardized_reactant)
            forward_reactants = standardized_reactants
        
        reactant_groups2.append(forward_reactants)

    return reactant_groups2

def save_reaction_visualization(reaction_name: str, forward_reactants: List[str], forward_products: List[List[str]], 
                               all_reverse_products: List[str], original_reactants_set: set, 
                               reverse_products_set: set, reactant_index: int, 
                               form_name: str, success: bool = True) -> None:
    """
    Save a visualization of the reaction pathway as PNG.
    
    Args:
        reaction_name: Name of the reaction
        forward_reactants: List of reactant SMILES
        forward_products: List of product sets from forward reaction
        all_reverse_products: List of reverse reaction products
        original_reactants_set: Set of cleaned original reactant SMILES
        reverse_products_set: Set of cleaned reverse product SMILES
        reactant_index: Index of the current reactant set
        form_name: The SMILES form tested (e.g., 'aromatic', 'kekule')
        success: Whether the reaction was successful
    """
    # Create a directory for reaction visualizations if it doesn't exist
    viz_dir = "reaction_visualizations"
    os.makedirs(viz_dir, exist_ok=True)

    # Create a safe filename
    safe_reaction_name = re.sub(r'[^\w\-_\.]', '_', reaction_name)
    
    # Get actual molecules for original reactants
    reactant_mols = [Chem.MolFromSmiles(smi) for smi in forward_reactants if Chem.MolFromSmiles(smi) is not None]
    
    # Get product molecules from forward reaction
    product_mols = []
    for reverse_reactants_set in forward_products:
        for product_smi in reverse_reactants_set:
            mol = Chem.MolFromSmiles(product_smi)
            if mol is not None:
                product_mols.append(mol)

    # Get reverse product molecules - use the cleaned set that's actually being compared
    reverse_mols = []
    for smi in reverse_products_set:
        mol = Chem.MolFromSmiles(smi)
        if mol is not None:
            reverse_mols.append(mol)

    # Create comprehensive visualization showing the full reaction pathway
    all_mols = reactant_mols + [None] + product_mols + [None] + reverse_mols
    legends = ([f"Reactant {i+1}" for i in range(len(reactant_mols))] + 
              ["→"] + 
              [f"Product {i+1}" for i in range(len(product_mols))] + 
              ["Reverse→"] + 
              [f"Reverse {i+1}" for i in range(len(reverse_mols))])

    # Add information about missing reactants if failed
    if not success:
        missing_reactants = original_reactants_set - reverse_products_set
        print(f"Missing from reverse products: {missing_reactants}")

    # Determine the status for filename
    status = "PASS" if success else "FAIL"
    
    # Save the comprehensive reaction pathway as PNG
    png_filename = f"{viz_dir}/{safe_reaction_name}_{reactant_index:03d}_{form_name}_{status}.png"
    
    try:
        # RDKit's MolsToGridImage returns a PIL Image when useSVG=False
        img = Draw.MolsToGridImage(all_mols, molsPerRow=max(len(reactant_mols), len(product_mols), len(reverse_mols)) + 1, 
                                  subImgSize=(200, 200), legends=legends, useSVG=False)
        # Save the PIL Image directly
        img.save(png_filename, "PNG")
        # print(f"Saved reaction visualization: {png_filename}")
    except Exception as e:
        print(f"Failed to save PNG visualization {png_filename}: {e}")
        # Fallback to SVG if PNG fails
        try:
            svg_filename = f"{viz_dir}/{safe_reaction_name}_{reactant_index:03d}_{form_name}_{status}.svg"
            img_svg = Draw.MolsToGridImage(all_mols, molsPerRow=max(len(reactant_mols), len(product_mols), len(reverse_mols)) + 1, 
                                          subImgSize=(200, 200), legends=legends, useSVG=True)
            with open(svg_filename, 'w') as f:
                f.write(img_svg)
            print(f"Saved SVG fallback: {svg_filename}")
        except Exception as e2:
            print(f"Failed to save SVG fallback: {e2}")

# --- MODIFIED FUNCTION ---
def execute_and_verify_reaction(
    reaction_name: str,
    reaction_info: dict,
    reactants_to_test: List[str],
    reactant_idx: int,
    form_name: str,
) -> ReactionStatus:
    """
    Runs the forward and reverse reaction for a given set of reactants and verifies the outcome.
    
    Returns:
        A ReactionStatus enum member indicating the outcome.
    """
    reaction_string = reaction_info["reaction_string"]
    reverse_reaction_strings = reaction_info.get("reverse_reaction_strings", [])

    # First, do the forward reaction
    forward_products = run_rxn(reaction_string, reactants_to_test)

    # Check if forward reaction failed to produce anything
    if not forward_products:
        print(f"INFO: No products generated for forward reaction ({form_name}): {reactants_to_test}")
        return ReactionStatus.FORWARD_FAILURE
    
    # Check if any products are None
    if any(p is None for t1 in forward_products for p in t1):
        print(f"Invalid products found in forward reaction for {reaction_name}: {forward_products}")
        return ReactionStatus.FORWARD_FAILURE

    # Now, apply each of the reverse reactions to each of the products
    all_reverse_products = []
    for reverse_reactants_set in forward_products:
        for reverse_reaction_string in reverse_reaction_strings:
            reverse_products = run_rxn(reverse_reaction_string, reverse_reactants_set, metadata=reactants_to_test)
            for r in reverse_products:
                all_reverse_products.extend(iter(r))
    
    # Convert everything to sets for comparison
    all_reverse_products_before_cleaning = set(all_reverse_products[:])
    original_reactants_set = {clean_up_smiles(p) for p in reactants_to_test if clean_up_smiles(p)}
    reverse_products_set = {clean_up_smiles(p) for p in all_reverse_products if clean_up_smiles(p)}

    if original_reactants_set.issubset(reverse_products_set):
        print(f"Passed! Reaction: {reaction_name}, Form: {form_name}")
        save_reaction_visualization(reaction_name, reactants_to_test, forward_products,
                                  all_reverse_products, original_reactants_set,
                                  reverse_products_set, reactant_idx, form_name, success=True)
        return ReactionStatus.SUCCESS
    else:
        # A reverse reaction failed. Generate the detailed prompt before returning.
        save_reaction_visualization(reaction_name, reactants_to_test, forward_products,
                                  all_reverse_products, original_reactants_set,
                                  reverse_products_set, reactant_idx, form_name, success=False)

        generate_llm_debug_prompt(
            reaction_name=reaction_name,
            form_name=form_name,
            forward_smarts=reaction_string,
            forward_reactants=reactants_to_test,
            forward_products=forward_products,
            reverse_smarts_list=reverse_reaction_strings,
            reverse_products_raw=all_reverse_products_before_cleaning,
            original_reactants_cleaned=original_reactants_set,
            reverse_products_cleaned=reverse_products_set,
        )
        return ReactionStatus.REVERSE_FAILURE

# --- MAIN EXECUTION LOGIC ---

with open("reactions.json", "r") as file:
    contents = file.read()
    # Replace some placeholders
    contents = contents.replace("AZIDE_SEARCH", "[$(N=[N+]=[N-]),$([N-][N+]#N)]")
    reactions = json.loads(contents)

validate_functional_group_defs(reactions)

if len(sys.argv) > 1:
    # If a specific reaction is provided as an argument, filter the reactions
    specific_reaction = sys.argv[1]
    
    # Check if the argument is a number
    if specific_reaction.isdigit():
        # Find reaction by RXN_NUM
        target_rxn_num = int(specific_reaction)
        reactions = {k: v for k, v in reactions.items() if v.get("RXN_NUM") == target_rxn_num}
        if not reactions:
            print(f"No reaction found with RXN_NUM: {target_rxn_num}")
            sys.exit(1)
    else:
        # Find reaction by name (current behavior)
        reactions = {k: v for k, v in reactions.items() if k == specific_reaction}
        if not reactions:
            print(f"No reaction found with name: {specific_reaction}")
            sys.exit(1)

for reaction_idx, reaction_name in enumerate(reactions):
    if "SKIP" in reaction_name:
        print(f"Skipping reaction: {reaction_name} >> ")
        continue

    reaction_info = reactions[reaction_name]
    functional_groups = reaction_info.get("functional_groups", [])
    if not functional_groups:
        print(f"No functional groups defined for reaction: {reaction_name}")
        continue

    debug_prereactions = reaction_info.get("debug_prereaction", None)
    if debug_prereactions:
        print(f"Found debug prereactions for {reaction_name}: {debug_prereactions}")

    reactant_groups = get_forward_reactant_groups(functional_groups, debug_prereactions)
    num_passed = 0
    num_tested = 0
    num_forward_failures = 0
    
    for reactant_idx, forward_reactants_raw in enumerate(reactant_groups):
        num_tested += 1
        # print(f"\n===== Testing Set {reactant_idx} for {reaction_name} =====")
        
        # Clean reactants first and create Mol objects
        cleaned_reactants = [clean_up_smiles(r) for r in forward_reactants_raw]
        if None in cleaned_reactants:
            print(f"SKIPPING: Invalid reactants found after cleaning for {reaction_name}: {forward_reactants_raw}")
            continue
        
        mols = [Chem.MolFromSmiles(s) for s in cleaned_reactants]
        if any(m is None for m in mols):
            print(f"SKIPPING: Could not create molecules for cleaned reactants: {cleaned_reactants}")
            continue

        # Sanitize and generate both aromatic and Kekule forms
        for mol in mols:
            Chem.SanitizeMol(mol)
        
        aromatic_reactants = [Chem.MolToSmiles(m, canonical=True, kekuleSmiles=False) for m in mols]
        kekule_reactants = [Chem.MolToSmiles(m, canonical=True, kekuleSmiles=True) for m in mols]

        # --- Test Aromatic Form ---
        aromatic_status = execute_and_verify_reaction(
            reaction_name, reaction_info, aromatic_reactants, reactant_idx, "aromatic"
        )
        if aromatic_status == ReactionStatus.REVERSE_FAILURE:
            # The detailed debug prompt has already been printed.
            raise AssertionError(f"FATAL: Reverse reaction for '{reaction_name}' failed on AROMATIC form. See debug prompt above.")
        
        # --- Test Kekule Form ---
        kekule_status = ReactionStatus.SUCCESS
        if aromatic_reactants != kekule_reactants:
            kekule_status = execute_and_verify_reaction(
                reaction_name, reaction_info, kekule_reactants, reactant_idx, "kekule"
            )
            if kekule_status == ReactionStatus.REVERSE_FAILURE:
                 # The detailed debug prompt has already been printed.
                 raise AssertionError(f"FATAL: Reverse reaction for '{reaction_name}' failed on KEKULE form. See debug prompt above.")
        else:
            #  print(f"Kekule form is identical to aromatic for set {reactant_idx}, skipping separate test.")
             kekule_status = aromatic_status
        
        # Tally results for the set
        if aromatic_status == ReactionStatus.SUCCESS and kekule_status == ReactionStatus.SUCCESS:
            num_passed += 1
        elif aromatic_status == ReactionStatus.FORWARD_FAILURE or kekule_status == ReactionStatus.FORWARD_FAILURE:
            num_forward_failures += 1
            print(f"NOTE: Set {reactant_idx} for {reaction_name} logged as a FORWARD FAILURE.")

    # Final summary for the reaction
    print(f"\nFINAL SUMMARY for {reaction_name}:")
    print(f"  - Total Sets Tested: {num_tested}")
    print(f"  - Passed Sets: {num_passed}")
    print(f"  - Forward Reaction Failures: {num_forward_failures}")

    if num_passed == 0 and num_tested > 0:
        print(f"\nWARNING: No reactant sets fully passed validation for {reaction_name}.")
    elif num_tested > 0:
        print(f"\nSUCCESS: {num_passed}/{num_tested} reactant sets passed for {reaction_name}.\n")