name: Autogrow5

channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.9
  - pip=24.0
  - setuptools=79.0.1
  - numpy=1.24.4
  - scipy=1.11.4
  - pandas=1.4.4
  - scikit-learn=1.5.1
  - matplotlib=3.8.3
  - pip:
      - numba==0.56.4
      - rdkit==2024.3.1
      - wget
      - prolif==2.0.3
      - deepfrag2==2.0.0

