name: Autogrow2

channels:
  - anaconda
  - conda-forge
  - numba
  - pytorch
  - pyg
  - nodefaults

dependencies:
  - python=3.9
  - flake8=4.0.1
  - mypy=0.812
  - pytest=7.1.2
  - numba=0.56.4
  - pytorch=1.11.0=py3.9_cuda11.3_cudnn8_0
  - torchvision=0.12.0=py39_cu113
  - torchaudio=0.11.0=py39_cu113
  - cudatoolkit=11.3
  - pytorch-lightning=1.7.1
  - pandas=1.4.4
  - rdkit=2024.03
  - k3d=2.15.2
  - py3dmol=2.4.0
  - h5py=3.7.0
  - scikit-learn=1.5.1
  - torchinfo=1.8.0
  - wandb=0.15.8
  - pyg
  - filelock=3.13.1
  - regex
  - sacremoses=0.0.53
  - sentencepiece=0.2.0
  - tokenizers=0.20.0
  - torchmetrics=0.11.0
  - pip=24.0
  - pip:
      - ProDy==2.4.1
      - numpy==1.23.5
      - scipy==1.11.4
      - matplotlib==3.8.3
      - Fancy-aggregations
      - wget
      - fair-esm
