name: Autogrow4

channels:
  - nodefaults

dependencies:
  - python=3.9
  - pip=24.0
  - pip:
      - flake8==4.0.1
      - mypy==0.812
      - pytest==7.1.2
      - numpy==1.22.3
      - numba==0.56.4
      - ProDy==2.4.1
      - --extra-index-url https://download.pytorch.org/whl/cu113
      - torch==1.11.0+cu113
      - torchvision==0.12.0+cu113
      - torchaudio==0.11.0
      - pytorch-lightning==1.7.1
      - scipy==1.11.4
      - pandas==1.4.4
      - rdkit==2024.3.1
      - k3d==2.15.2
      - py3Dmol==2.4.0
      - h5py==3.7.0
      - scikit-learn==1.5.1
      - torchinfo==1.8.0
      - wandb==0.15.8      -
      - -f https://data.pyg.org/whl/torch-1.11.0+cu113.html
      - torch_geometric
      - filelock==3.13.1
      - regex
      - sacremoses==0.0.53
      - sentencepiece==0.2.0
      - tokenizers==0.20.0
      - torchmetrics==0.11.0
      - matplotlib==3.8.3
      - Fancy-aggregations
      - wget
      - fair-esm
