name: Autogrow5

channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.9
  - pip=24.0
  - setuptools=79.0.1
  - biopython
  - numpy=1.24.4
  - scipy=1.11.4
  - pandas=1.4.4
  - scikit-learn=1.5.1
  - matplotlib=3.8.3
  - h5py=3.7.0
  - flake8=4.0.1
  - mypy
  - pytest=7.1.2
  - ProDy=2.4.1
  - pip:
      - torch==1.11.0
      - torchvision==0.12.0
      - torchaudio==0.11.0
      - numba==0.56.4
      - pytorch-lightning==1.7.1
      - rdkit==2024.3.1
      - k3d==2.15.2
      - py3Dmol==2.4.0
      - torchinfo==1.8.0
      - wandb==0.15.8
      - torch_geometric -f https://data.pyg.org/whl/torch-1.11.0+cpu.html
      - filelock==3.13.1
      - regex
      - sacremoses==0.0.53
      - sentencepiece==0.2.0
      - tokenizers==0.20.0
      - torchmetrics==0.11.0
      - protobuf==3.20.3
      - Fancy-aggregations
      - wget
      - fair-esm
      - prolif==2.0.3

